service: course-app

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  app:
    handler: handler.app
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline

resources:
  Resources:
    CoursesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Courses
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    CourseDatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CourseDates
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: course_id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: course_id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    ParticipantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Participants
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: course_id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: course_id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    SignInSheetsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SignInSheets
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: course_date_id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: course_date_id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5